version: '3.8'

services:
  frontend:
    image: macikel/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: macikel/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_DATABASE: todoapp
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: todoapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
